---
- name: update ubuntu servers
  hosts: ubuntu
  become: yes

  tasks:
  - name: ensure web server is installed
    package:
      name: apache2
      state: present

  - name: ensure web server is started
    service:
      name: apache2
      state: started

  - name: ensure web server is started
    service:
      name: apache2
      enabled: yes
...


