---
- name: update web servers
  hosts: all
  become: yes

  tasks:
  - name: ensure static page
    copy:
      src: static.html
      dest: /var/www/html/static.html
  
  - name: ensure static page
    template :
      src: dynamic.j2
      dest: /var/www/html/info.html
...


